"""Central configuration. Edit this file to change paths or hyperparameters globally."""
import os
from pathlib import Path

# --- Paths ---
ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "dataset"
OUTPUT_DIR = ROOT / "output"
FEATURES_DIR = OUTPUT_DIR / "features"
MODELS_DIR = OUTPUT_DIR / "models"
SUBMISSIONS_DIR = OUTPUT_DIR / "submissions"

for d in (FEATURES_DIR, MODELS_DIR, SUBMISSIONS_DIR):
    d.mkdir(parents=True, exist_ok=True)

# --- Reproducibility ---
SEED = 42

# --- Cross-validation ---
N_FOLDS = 5

# --- Base LM for logprob features ---
# Choose based on your VRAM and what you suspect the texts were generated by.
# Llama-3-8B is strong but gated on Hugging Face. Qwen2.5-1.5B is open and
# small enough for the current scratch quota. Override with BASE_LM_NAME=...
# when you have more cache space or an authenticated gated model.
BASE_LM_NAME = os.getenv("BASE_LM_NAME", "Qwen/Qwen2.5-1.5B")


def model_cache_tag(model_name: str) -> str:
    return (
        model_name.lower()
        .replace("/", "_")
        .replace("-", "_")
        .replace(".", "_")
    )


BASE_LM_TAG = os.getenv("BASE_LM_TAG", model_cache_tag(BASE_LM_NAME))

# Optional second model for Binoculars-style ratio features. Should be a smaller
# but related model (same tokenizer family is ideal but not required).
SECOND_LM_NAME = os.getenv("SECOND_LM_NAME", "Qwen/Qwen2.5-1.5B-Instruct")

# Embeddings model for frozen-features track (small, fast, strong on CPU/GPU)
EMB_MODEL_NAME = "microsoft/deberta-v3-base"

# --- Feature extraction ---
MAX_TOKENS = int(os.getenv("MAX_TOKENS", "512"))  # truncate very long texts; ~900 chars ≈ 200-250 tokens, so 512 is plenty
DEVICE = os.getenv("DEVICE", "cuda")  # set DEVICE=cpu only for debugging
LM_BATCH_SIZE = int(os.getenv("LM_BATCH_SIZE", "8"))  # tune to your VRAM

# --- LightGBM defaults (tuned for tiny datasets — strong regularization) ---
LGBM_PARAMS = {
    "objective": "binary",
    "metric": "auc",  # AUC is better proxy for TPR@FPR=0.01 than logloss
    "learning_rate": 0.03,
    "num_leaves": 15,
    "min_data_in_leaf": 10,
    "feature_fraction": 0.85,
    "bagging_fraction": 0.85,
    "bagging_freq": 5,
    "lambda_l2": 1.0,
    "verbose": -1,
    "seed": SEED,
}
LGBM_NUM_BOOST_ROUND = 2000
LGBM_EARLY_STOPPING = 100
